# -*- coding: utf-8 -*-
"""Question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZs1zefXIkeV5ixfyP0n6-ab51ObD9iK
"""

# #Step 1. Import the necessary libraries

import pandas as pd
import numpy as np



#Step 2. Import the dataset from this address.
#Step 3. Assign it to a variable called euro12.

euro12 = pd.read_csv('/content/main.csv')

euro12

#Step 4. Select only the Goal column.

euro12.Goals

#OR

euro12['Goals']

#Step 5. How many team participated in the Euro2012?

euro12.shape[0] #16 teams participated

#Step 6. What is the number of columns in the dataset?

euro12.shape[1]

#OReuro12.info()

#Alternatively
c = euro12.groupby('Team').sum()
c = c.sort_values(['Red Cards', 'Yellow Cards'], ascending = False)
c.iloc[:, -5:-3]

from google.colab import files
euro12.to_csv('Answer3.csv')
files.download('Answer3.csv')