# -*- coding: utf-8 -*-
"""Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l6L2MtcXNHQ1kbtU9iv3aucsYcwGwurF
"""

import pandas as pd
new = pd.read_csv("main.csv")

new.head()

new.Year = pd.to_datetime(new.Year,format='%Y')
new.Year

new = new.set_index('Year',drop=True)
new

del new['Total']
new.head()

new = new.resample('10AS').sum()

population = new['Population'].resample('10AS').max()
print(population)
new['Population'] = population
new

from google.colab import files
new.to_csv('Answer1.csv')
files.download('Answer1.csv')